#include "save/EventJson.h"

// Implements typed event-payload JSON conversion for schema v1 save files.
// This file is intentionally narrow: it knows about event payload shapes, but it
// does not know about tables, transactions, or the broader repository workflow.

#if __has_include(<nlohmann/json.hpp>)
#include <nlohmann/json.hpp>
#define DEEP_SIGNAL_HAS_NLOHMANN_JSON 1
#else
#define DEEP_SIGNAL_HAS_NLOHMANN_JSON 0
#endif

#include "sim/IdTypes.h"
#include "sim/Minerals.h"

#include <charconv>
#include <cmath>
#include <cstdint>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>
#include <type_traits>
#include <variant>

namespace deep::save {
namespace {

// Converts strongly typed IDs to their persisted integer representation.
template <typename IdT>
[[nodiscard]] std::int64_t idValue(const IdT id) noexcept {
    return id.value;
}

// Converts enum values to stable persisted ordinals. Schema migrations must
// account for any future enum reordering.
template <typename EnumT>
[[nodiscard]] std::int64_t enumValue(const EnumT value) noexcept {
    return static_cast<std::int64_t>(value);
}

// Validates enum ordinals read from JSON payloads before reconstructing typed
// event records. Payloads are part of the untrusted save boundary.
template <typename EnumT>
[[nodiscard]] bool isValidEnumValue(const std::int64_t value) noexcept {
    if constexpr (std::is_same_v<EnumT, Mineral>) {
        return value >= 0 && value < static_cast<std::int64_t>(mineralCount());
    } else {
        static_assert(std::is_enum_v<EnumT>, "enumFromValue requires an enum type");
        return false;
    }
}

template <typename EnumT>
[[nodiscard]] EnumT enumFromValue(const std::int64_t value) {
    if (!isValidEnumValue<EnumT>(value)) {
        throw std::runtime_error{"Save event payload contains an invalid enum value"};
    }
    return static_cast<EnumT>(value);
}

// Converts JSON integer payload values to int after checking range. This mirrors
// the repository's SQL integer narrowing guard for event-specific fields.
[[nodiscard]] int checkedIntFromPayload(const std::int64_t value, const std::string_view fieldName) {
    if (value < static_cast<std::int64_t>(std::numeric_limits<int>::min()) ||
        value > static_cast<std::int64_t>(std::numeric_limits<int>::max())) {
        throw std::runtime_error{std::string{"Save event integer is out of range for field: "} + std::string{fieldName}};
    }
    return static_cast<int>(value);
}

// Writes doubles with enough precision for a stable JSON audit payload.
[[nodiscard]] std::string numberToJson(const double value) {
    std::ostringstream out;
    out << std::setprecision(17) << value;
    return out.str();
}

// Escapes the small subset of JSON string characters emitted by this repository.
// Unicode escape decoding is not needed because the writer stores UTF-8 directly.
[[nodiscard]] std::string escapeJsonString(const std::string_view value) {
    std::string escaped;
    escaped.reserve(value.size() + 2);
    for (const char ch : value) {
        switch (ch) {
        case '"':
            escaped += "\\\"";
            break;
        case '\\':
            escaped += "\\\\";
            break;
        case '\n':
            escaped += "\\n";
            break;
        case '\r':
            escaped += "\\r";
            break;
        case '\t':
            escaped += "\\t";
            break;
        default:
            escaped += ch;
            break;
        }
    }
    return escaped;
}

// Unescapes strings generated by escapeJsonString. Unsupported escape sequences
// are treated as malformed save data and reported through an exception.
[[nodiscard]] std::string unescapeJsonString(const std::string_view value) {
    std::string unescaped;
    unescaped.reserve(value.size());
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (value[i] != '\\') {
            unescaped += value[i];
            continue;
        }

        if (i + 1 >= value.size()) {
            throw std::runtime_error{"Malformed JSON escape in save payload"};
        }

        ++i;
        switch (value[i]) {
        case '"':
            unescaped += '"';
            break;
        case '\\':
            unescaped += '\\';
            break;
        case 'n':
            unescaped += '\n';
            break;
        case 'r':
            unescaped += '\r';
            break;
        case 't':
            unescaped += '\t';
            break;
        default:
            throw std::runtime_error{"Unsupported JSON escape in save payload"};
        }
    }
    return unescaped;
}

// Performs the first envelope check for schema v1 event payloads. The parser is
// intentionally limited to the typed event shapes below rather than exposing a
// generic JSON abstraction to the save repository.
void requireFlatJsonObjectShape(const std::string_view json) {
    if (json.size() < 2 || json.front() != '{' || json.back() != '}') {
        throw std::runtime_error{"Malformed event payload JSON object"};
    }
}

// Returns the serialized field value for a flat JSON object generated by this
// module. Unknown payload grammar is rejected by the event-specific readers
// instead of being silently ignored by SaveGameRepository.
[[nodiscard]] std::string jsonFieldRaw(const std::string_view json, const std::string_view key) {
    requireFlatJsonObjectShape(json);

    const std::string needle = '"' + std::string{key} + "\":";
    const std::size_t keyPos = json.find(needle);
    if (keyPos == std::string_view::npos) {
        throw std::runtime_error{"Missing field in event payload JSON"};
    }

    std::size_t valuePos = keyPos + needle.size();
    if (valuePos >= json.size()) {
        throw std::runtime_error{"Malformed event payload JSON"};
    }

    if (json[valuePos] == '"') {
        ++valuePos;
        std::string raw;
        bool escaped = false;
        for (; valuePos < json.size(); ++valuePos) {
            const char ch = json[valuePos];
            if (!escaped && ch == '"') {
                return raw;
            }
            if (!escaped && ch == '\\') {
                escaped = true;
                raw += ch;
                continue;
            }
            escaped = false;
            raw += ch;
        }
        throw std::runtime_error{"Unterminated JSON string in event payload"};
    }

    const std::size_t end = json.find_first_of(",}", valuePos);
    if (end == std::string_view::npos) {
        throw std::runtime_error{"Malformed event payload JSON value"};
    }
    return std::string{json.substr(valuePos, end - valuePos)};
}

[[nodiscard]] std::int64_t jsonInt64(const std::string_view json, const std::string_view key) {
    const std::string raw = jsonFieldRaw(json, key);
    std::int64_t value = 0;
    const auto* begin = raw.data();
    const auto* end = raw.data() + raw.size();
    const auto [ptr, ec] = std::from_chars(begin, end, value);
    if (ec != std::errc{} || ptr != end) {
        throw std::runtime_error{"Invalid integer in event payload JSON"};
    }
    return value;
}

[[nodiscard]] double jsonDouble(const std::string_view json, const std::string_view key) {
    const std::string raw = jsonFieldRaw(json, key);
    double value = 0.0;
    const auto* begin = raw.data();
    const auto* end = raw.data() + raw.size();
    const auto [ptr, ec] = std::from_chars(begin, end, value);
    if (ec != std::errc{} || ptr != end || !std::isfinite(value)) {
        throw std::runtime_error{"Invalid double in event payload JSON"};
    }
    return value;
}

[[nodiscard]] std::string jsonString(const std::string_view json, const std::string_view key) {
    return unescapeJsonString(jsonFieldRaw(json, key));
}

[[nodiscard]] std::string quoteJson(const std::string_view value) {
    return '"' + escapeJsonString(value) + '"';
}

} // namespace

[[nodiscard]] std::string eventTypeName(const SimEventPayload& payload) {
    return std::visit([](const auto& event) -> std::string {
        using Event = std::decay_t<decltype(event)>;
        if constexpr (std::is_same_v<Event, MineralExtractedEvent>) {
            return "mineral_extracted";
        } else if constexpr (std::is_same_v<Event, ShipyardOrderCreatedEvent>) {
            return "shipyard_order_created";
        } else if constexpr (std::is_same_v<Event, ShipCompletedEvent>) {
            return "ship_completed";
        } else if constexpr (std::is_same_v<Event, FleetOrderAssignedEvent>) {
            return "fleet_order_assigned";
        } else if constexpr (std::is_same_v<Event, FleetArrivedEvent>) {
            return "fleet_arrived";
        } else if constexpr (std::is_same_v<Event, CommandRejectedEvent>) {
            return "command_rejected";
        }
    }, payload);
}

[[nodiscard]] std::string eventPayloadToJson(const SimEventPayload& payload) {
#if DEEP_SIGNAL_HAS_NLOHMANN_JSON
    return std::visit([](const auto& event) -> std::string {
        using Event = std::decay_t<decltype(event)>;
        nlohmann::json object = nlohmann::json::object();

        if constexpr (std::is_same_v<Event, MineralExtractedEvent>) {
            object["colony_id"] = idValue(event.colonyId);
            object["body_id"] = idValue(event.bodyId);
            object["mineral"] = enumValue(event.mineral);
            object["amount"] = event.amount;
            object["remaining_deposit"] = event.remainingDeposit;
        } else if constexpr (std::is_same_v<Event, ShipyardOrderCreatedEvent>) {
            object["order_id"] = idValue(event.orderId);
            object["colony_id"] = idValue(event.colonyId);
            object["ship_class_id"] = idValue(event.shipClassId);
            object["quantity"] = event.quantity;
        } else if constexpr (std::is_same_v<Event, ShipCompletedEvent>) {
            object["order_id"] = idValue(event.orderId);
            object["colony_id"] = idValue(event.colonyId);
            object["ship_id"] = idValue(event.shipId);
            object["fleet_id"] = idValue(event.fleetId);
            object["ship_class_id"] = idValue(event.shipClassId);
        } else if constexpr (std::is_same_v<Event, FleetOrderAssignedEvent>) {
            object["fleet_id"] = idValue(event.fleetId);
            object["origin_body_id"] = idValue(event.originBodyId);
            object["destination_body_id"] = idValue(event.destinationBodyId);
            object["days_remaining"] = event.daysRemaining;
        } else if constexpr (std::is_same_v<Event, FleetArrivedEvent>) {
            object["fleet_id"] = idValue(event.fleetId);
            object["destination_body_id"] = idValue(event.destinationBodyId);
        } else if constexpr (std::is_same_v<Event, CommandRejectedEvent>) {
            object["reason"] = event.reason;
        }

        return object.dump();
    }, payload);
#else
    return std::visit([](const auto& event) -> std::string {
        using Event = std::decay_t<decltype(event)>;
        std::ostringstream out;
        out << '{';

        if constexpr (std::is_same_v<Event, MineralExtractedEvent>) {
            out << "\"colony_id\":" << idValue(event.colonyId)
                << ",\"body_id\":" << idValue(event.bodyId)
                << ",\"mineral\":" << enumValue(event.mineral)
                << ",\"amount\":" << numberToJson(event.amount)
                << ",\"remaining_deposit\":" << numberToJson(event.remainingDeposit);
        } else if constexpr (std::is_same_v<Event, ShipyardOrderCreatedEvent>) {
            out << "\"order_id\":" << idValue(event.orderId)
                << ",\"colony_id\":" << idValue(event.colonyId)
                << ",\"ship_class_id\":" << idValue(event.shipClassId)
                << ",\"quantity\":" << event.quantity;
        } else if constexpr (std::is_same_v<Event, ShipCompletedEvent>) {
            out << "\"order_id\":" << idValue(event.orderId)
                << ",\"colony_id\":" << idValue(event.colonyId)
                << ",\"ship_id\":" << idValue(event.shipId)
                << ",\"fleet_id\":" << idValue(event.fleetId)
                << ",\"ship_class_id\":" << idValue(event.shipClassId);
        } else if constexpr (std::is_same_v<Event, FleetOrderAssignedEvent>) {
            out << "\"fleet_id\":" << idValue(event.fleetId)
                << ",\"origin_body_id\":" << idValue(event.originBodyId)
                << ",\"destination_body_id\":" << idValue(event.destinationBodyId)
                << ",\"days_remaining\":" << event.daysRemaining;
        } else if constexpr (std::is_same_v<Event, FleetArrivedEvent>) {
            out << "\"fleet_id\":" << idValue(event.fleetId)
                << ",\"destination_body_id\":" << idValue(event.destinationBodyId);
        } else if constexpr (std::is_same_v<Event, CommandRejectedEvent>) {
            out << "\"reason\":" << quoteJson(event.reason);
        }

        out << '}';
        return out.str();
    }, payload);
#endif
}

[[nodiscard]] SimEventPayload eventPayloadFromJson(const std::string_view eventType, const std::string_view payloadJson) {
#if DEEP_SIGNAL_HAS_NLOHMANN_JSON
    const nlohmann::json object = nlohmann::json::parse(payloadJson.begin(), payloadJson.end());
    if (!object.is_object()) {
        throw std::runtime_error{"Malformed event payload JSON object"};
    }

    const auto requireInt64 = [&object](const std::string_view key) -> std::int64_t {
        const auto it = object.find(std::string{key});
        if (it == object.end() || !it->is_number_integer()) {
            throw std::runtime_error{"Missing or invalid integer in event payload JSON"};
        }
        return it->get<std::int64_t>();
    };

    const auto requireDouble = [&object](const std::string_view key) -> double {
        const auto it = object.find(std::string{key});
        if (it == object.end() || !it->is_number()) {
            throw std::runtime_error{"Missing or invalid number in event payload JSON"};
        }
        const double value = it->get<double>();
        if (!std::isfinite(value)) {
            throw std::runtime_error{"Invalid double in event payload JSON"};
        }
        return value;
    };

    const auto requireString = [&object](const std::string_view key) -> std::string {
        const auto it = object.find(std::string{key});
        if (it == object.end() || !it->is_string()) {
            throw std::runtime_error{"Missing or invalid string in event payload JSON"};
        }
        return it->get<std::string>();
    };

    if (eventType == "mineral_extracted") {
        return MineralExtractedEvent{
            .colonyId = ColonyId{requireInt64("colony_id")},
            .bodyId = BodyId{requireInt64("body_id")},
            .mineral = enumFromValue<Mineral>(requireInt64("mineral")),
            .amount = requireDouble("amount"),
            .remainingDeposit = requireDouble("remaining_deposit")
        };
    }

    if (eventType == "shipyard_order_created") {
        return ShipyardOrderCreatedEvent{
            .orderId = ShipyardOrderId{requireInt64("order_id")},
            .colonyId = ColonyId{requireInt64("colony_id")},
            .shipClassId = ShipClassId{requireInt64("ship_class_id")},
            .quantity = checkedIntFromPayload(requireInt64("quantity"), "event.quantity")
        };
    }

    if (eventType == "ship_completed") {
        return ShipCompletedEvent{
            .orderId = ShipyardOrderId{requireInt64("order_id")},
            .colonyId = ColonyId{requireInt64("colony_id")},
            .shipId = ShipId{requireInt64("ship_id")},
            .fleetId = FleetId{requireInt64("fleet_id")},
            .shipClassId = ShipClassId{requireInt64("ship_class_id")}
        };
    }

    if (eventType == "fleet_order_assigned") {
        return FleetOrderAssignedEvent{
            .fleetId = FleetId{requireInt64("fleet_id")},
            .originBodyId = BodyId{requireInt64("origin_body_id")},
            .destinationBodyId = BodyId{requireInt64("destination_body_id")},
            .daysRemaining = checkedIntFromPayload(requireInt64("days_remaining"), "event.days_remaining")
        };
    }

    if (eventType == "fleet_arrived") {
        return FleetArrivedEvent{
            .fleetId = FleetId{requireInt64("fleet_id")},
            .destinationBodyId = BodyId{requireInt64("destination_body_id")}
        };
    }

    if (eventType == "command_rejected") {
        return CommandRejectedEvent{.reason = requireString("reason")};
    }

    throw std::runtime_error{"Unknown event type in save file"};
#else

    if (eventType == "mineral_extracted") {
        return MineralExtractedEvent{
            .colonyId = ColonyId{jsonInt64(payloadJson, "colony_id")},
            .bodyId = BodyId{jsonInt64(payloadJson, "body_id")},
            .mineral = enumFromValue<Mineral>(jsonInt64(payloadJson, "mineral")),
            .amount = jsonDouble(payloadJson, "amount"),
            .remainingDeposit = jsonDouble(payloadJson, "remaining_deposit")
        };
    }

    if (eventType == "shipyard_order_created") {
        return ShipyardOrderCreatedEvent{
            .orderId = ShipyardOrderId{jsonInt64(payloadJson, "order_id")},
            .colonyId = ColonyId{jsonInt64(payloadJson, "colony_id")},
            .shipClassId = ShipClassId{jsonInt64(payloadJson, "ship_class_id")},
            .quantity = checkedIntFromPayload(jsonInt64(payloadJson, "quantity"), "event.quantity")
        };
    }

    if (eventType == "ship_completed") {
        return ShipCompletedEvent{
            .orderId = ShipyardOrderId{jsonInt64(payloadJson, "order_id")},
            .colonyId = ColonyId{jsonInt64(payloadJson, "colony_id")},
            .shipId = ShipId{jsonInt64(payloadJson, "ship_id")},
            .fleetId = FleetId{jsonInt64(payloadJson, "fleet_id")},
            .shipClassId = ShipClassId{jsonInt64(payloadJson, "ship_class_id")}
        };
    }

    if (eventType == "fleet_order_assigned") {
        return FleetOrderAssignedEvent{
            .fleetId = FleetId{jsonInt64(payloadJson, "fleet_id")},
            .originBodyId = BodyId{jsonInt64(payloadJson, "origin_body_id")},
            .destinationBodyId = BodyId{jsonInt64(payloadJson, "destination_body_id")},
            .daysRemaining = checkedIntFromPayload(jsonInt64(payloadJson, "days_remaining"), "event.days_remaining")
        };
    }

    if (eventType == "fleet_arrived") {
        return FleetArrivedEvent{
            .fleetId = FleetId{jsonInt64(payloadJson, "fleet_id")},
            .destinationBodyId = BodyId{jsonInt64(payloadJson, "destination_body_id")}
        };
    }

    if (eventType == "command_rejected") {
        return CommandRejectedEvent{.reason = jsonString(payloadJson, "reason")};
    }

    throw std::runtime_error{"Unknown event type in save file"};

#endif
}



} // namespace deep::save
