#pragma once

// Contains plain simulation domain records for Prototype 0.1.
// These structs intentionally avoid behavior-heavy inheritance so GameState can
// own data by value and the future SQLite layer can map records directly.

#include "sim/IdTypes.h"
#include "sim/Minerals.h"

#include <optional>
#include <string>
#include <vector>

namespace deep {

// A star system container. Prototype 0.1 starts with a single Sol system.
struct StarSystem {
    StarSystemId id;
    std::string name;
};

// Coarse body classification for map display and future rule branching.
enum class BodyType {
    Star,
    Terrestrial,
    GasGiant,
    Moon,
    Asteroid
};

// A body in a star system. Coordinates are abstract map coordinates, not orbital
// mechanics; this keeps movement deterministic for the first vertical slice.
struct Body {
    BodyId id;
    StarSystemId systemId;
    std::string name;
    BodyType type = BodyType::Terrestrial;
    double x = 0.0;
    double y = 0.0;
};

// A mineable deposit on a body. Accessibility is a multiplier in [0, 1+] for now;
// values above 1.0 can model unusually rich deposits in later scenario data.
struct MineralDeposit {
    BodyId bodyId;
    Mineral mineral = Mineral::Iron;
    double remaining = 0.0;
    double accessibility = 1.0;
};

// A settled body with stockpiles and industrial capacity. mines controls daily
// extraction, while shipyardCapacity controls build points applied per day.
struct Colony {
    ColonyId id;
    BodyId bodyId;
    std::string name;
    MineralSet stockpile;
    double mines = 0.0;
    double shipyardCapacity = 0.0;
};

// Prototype ship roles used for filtering and future UI grouping.
enum class ShipRole {
    Survey,
    Freighter,
    Escort
};

// Buildable ship class definition. In Prototype 0.1 these are hardcoded scenario
// records; later they can be generated by a ship designer or data files.
struct ShipClass {
    ShipClassId id;
    std::string name;
    ShipRole role = ShipRole::Survey;
    MineralSet buildCost;
    double buildPoints = 0.0;
    double speedKmPerDay = 0.0;
    double fuelCapacity = 0.0;
};

// Order lifecycle for shipyard production.
// Only states produced by valid Prototype 0.1 simulation ticks are modeled here.
// Recoverable mineral shortages keep an order Active rather than introducing a
// separate paused/blocked state.
enum class ShipyardOrderStatus {
    Active,
    Completed
};

// A production order assigned to a colony shipyard. quantityCompleted allows
// multi-ship orders to continue across multiple completions.
struct ShipyardOrder {
    ShipyardOrderId id;
    ColonyId colonyId;
    ShipClassId shipClassId;
    int quantityRequested = 1;
    int quantityCompleted = 0;
    double accumulatedBuildPoints = 0.0;
    ShipyardOrderStatus status = ShipyardOrderStatus::Active;
};

// A constructed ship. Ships are assigned to exactly one fleet in this prototype.
struct Ship {
    ShipId id;
    ShipClassId shipClassId;
    std::string name;
    FleetId fleetId;
    double fuel = 0.0;
};

// Fleet order type. Only body-to-body movement exists in Prototype 0.1.
enum class FleetOrderType {
    None,
    MoveToBody
};

// Active fleet order state. targetBodyId is optional so invalid or cleared orders
// can be represented explicitly during validation and save/load repair.
struct FleetOrder {
    FleetOrderType type = FleetOrderType::None;
    std::optional<BodyId> targetBodyId;
    int daysRemaining = 0;
};

// A group of ships sharing a location and one active order. shipIds reference
// GameState::ships records; the fleet does not own ship memory.
struct Fleet {
    FleetId id;
    std::string name;
    BodyId currentBodyId;
    std::optional<BodyId> destinationBodyId;
    std::vector<ShipId> shipIds;
    FleetOrder activeOrder;
};

} // namespace deep
