#pragma once

// Defines typed simulation audit events and lightweight economy telemetry.
// Audit events are consumed by tests, the CLI, the desktop UI, and the
// SQLite persistence layer; telemetry is for high-volume daily facts that should
// not spam the player-facing event log.

#include "sim/IdTypes.h"
#include "sim/Minerals.h"

#include <cstdint>
#include <string>
#include <variant>

namespace deep {

// Severity lets UI and tests distinguish informational events from warnings or
// future critical simulation failures.
enum class EventSeverity {
    Info,
    Warning,
    Critical
};

// Retained event payload for historical mineral extraction audit entries.
// New daily mining output is captured as DailyEconomySnapshot telemetry so the
// player-facing event log stays focused on major audit events.
struct MineralExtractedEvent {
    ColonyId colonyId;
    BodyId bodyId;
    Mineral mineral = Mineral::Iron;
    double amount = 0.0;
    double remainingDeposit = 0.0;
};

// One row of daily economy telemetry generated by the mining tick. These rows
// support graphs, forecasts, and debug inspection without treating routine
// extraction as player-facing audit history.
struct DailyEconomySnapshot {
    std::int64_t day = 0;
    ColonyId colonyId;
    BodyId bodyId;
    Mineral mineral = Mineral::Iron;
    double amount = 0.0;
    double remainingDeposit = 0.0;
};

// Emitted when a shipyard build command is accepted.
struct ShipyardOrderCreatedEvent {
    ShipyardOrderId orderId;
    ColonyId colonyId;
    ShipClassId shipClassId;
    int quantity = 1;
};

// Emitted once per completed ship. Prototype 0.1 creates one new fleet for each
// completed ship to keep movement testing simple and explicit.
struct ShipCompletedEvent {
    ShipyardOrderId orderId;
    ColonyId colonyId;
    ShipId shipId;
    FleetId fleetId;
    ShipClassId shipClassId;
};

// Emitted when a fleet movement command is accepted.
struct FleetOrderAssignedEvent {
    FleetId fleetId;
    BodyId originBodyId;
    BodyId destinationBodyId;
    int daysRemaining = 0;
};

// Emitted when a fleet movement order reaches its target body.
struct FleetArrivedEvent {
    FleetId fleetId;
    BodyId destinationBodyId;
};

// Emitted after a resource survey improves one or more low-confidence deposits
// on the target body. Confidence fields are averages across changed deposits so
// the event remains compact while still explaining the survey result.
struct ResourceSurveyCompletedEvent {
    FleetId fleetId;
    BodyId bodyId;
    int depositsImproved = 0;
    double averageConfidenceBefore = 0.0;
    double averageConfidenceAfter = 0.0;
};

// Emitted when validation rejects a command or a daily process detects invalid
// state. The reason should be precise enough for UI display and test assertions.
struct CommandRejectedEvent {
    std::string reason;
};

// Variant envelope for all event payloads. Adding a new event type requires
// updating persistence serialization and CLI/UI visitors.
using SimEventPayload = std::variant<
    MineralExtractedEvent,
    ShipyardOrderCreatedEvent,
    ShipCompletedEvent,
    FleetOrderAssignedEvent,
    FleetArrivedEvent,
    ResourceSurveyCompletedEvent,
    CommandRejectedEvent
>;

// Full event record. id is monotonic within a GameState; day is captured when
// the event is emitted so later UI filtering does not depend on current time.
// Payload IDs must still resolve to live records during state validation; entity
// deletion will need an explicit historical-reference policy before it is added.
struct SimEvent {
    EventId id;
    std::int64_t day = 0;
    EventSeverity severity = EventSeverity::Info;
    SimEventPayload payload;
};

} // namespace deep
