#pragma once

// Defines typed simulation audit events and lightweight economy telemetry.
// Audit events are consumed by tests, the CLI, the desktop UI, and the
// SQLite persistence layer; telemetry is for high-volume daily facts that should
// not spam the player-facing event log.

#include "sim/IdTypes.h"
#include "sim/Minerals.h"
#include "sim/SurveyProgram.h"

#include <cstdint>
#include <optional>
#include <string>
#include <variant>

namespace deep {

// Severity lets UI and tests distinguish informational events from warnings or
// future critical simulation failures.
enum class EventSeverity {
    Info,
    Warning,
    Critical
};

// Retained event payload for historical mineral extraction audit entries.
// New daily mining output is captured as DailyEconomySnapshot telemetry so the
// player-facing event log stays focused on major audit events.
struct MineralExtractedEvent {
    ColonyId colonyId;
    BodyId bodyId;
    Mineral mineral = Mineral::Iron;
    double amount = 0.0;
    double remainingDeposit = 0.0;
};

// One row of daily economy telemetry generated by the mining tick. These rows
// support graphs, forecasts, and debug inspection without treating routine
// extraction as player-facing audit history.
struct DailyEconomySnapshot {
    std::int64_t day = 0;
    ColonyId colonyId;
    BodyId bodyId;
    Mineral mineral = Mineral::Iron;
    double amount = 0.0;
    double remainingDeposit = 0.0;
};

// Emitted when a shipyard build command is accepted.
struct ShipyardOrderCreatedEvent {
    ShipyardOrderId orderId;
    ColonyId colonyId;
    ShipClassId shipClassId;
    int quantity = 1;
};

// Audit identity for a newly saved design. Components live in the immutable
// class record; event payloads need only identify its revision and lineage.
struct ShipClassRevisionCreatedEvent {
    ShipClassId shipClassId;
    std::optional<ShipClassId> basedOnClassId;
    int revision = 1;
};

// Emitted once per completed ship. Prototype 0.1 creates one new fleet for each
// completed ship to keep movement testing simple and explicit.
struct ShipCompletedEvent {
    ShipyardOrderId orderId;
    ColonyId colonyId;
    ShipId shipId;
    FleetId fleetId;
    ShipClassId shipClassId;
};

// Emitted when a fleet movement command is accepted.
struct FleetOrderAssignedEvent {
    FleetId fleetId;
    BodyId originBodyId;
    BodyId destinationBodyId;
    int daysRemaining = 0;
};

// Emitted when a fleet movement order reaches its target body.
struct FleetArrivedEvent {
    FleetId fleetId;
    BodyId destinationBodyId;
};

// Emitted after an immediate survey or completed timed visit. A valid pass may
// improve zero deposits; then both confidence averages are zero.
struct ResourceSurveyCompletedEvent {
    FleetId fleetId;
    BodyId bodyId;
    int depositsImproved = 0;
    double averageConfidenceBefore = 0.0;
    double averageConfidenceAfter = 0.0;
};

enum class SurveyProgramAuditKind {
    Authorized,
    Amended,
    Suspended,
    Resumed,
    CancelRequested,
    Closed,
    TaskSelected,
    FuelTransferred,
    VisitCompleted,
    ReportPublished,
    IssueRaised,
    IssueAcknowledged
};

// One typed program audit envelope. Optional identities identify the physical
// action when applicable; detail explains the decision without becoming state.
struct SurveyProgramAuditEvent {
    SurveyProgramId programId;
    SurveyProgramAuditKind kind = SurveyProgramAuditKind::Authorized;
    std::optional<FleetId> fleetId = std::nullopt;
    std::optional<BodyId> bodyId = std::nullopt;
    std::optional<PersonId> leaderId = std::nullopt;
    SurveyPlanningApproach approach = SurveyPlanningApproach::CoverageFirst;
    int charterRevision = 1;
    int passNumber = 0;
    double fuelAmount = 0.0;
    std::string detail{};
};

// Freight audits carry typed custody identity; Departure amounts are actual
// engine burn, while Transfer detail/receipts distinguish inventory transfers.
enum class FreightProgramAuditKind {
    Authorized, Amended, Suspended, Resumed, Cancelled, IssueAcknowledged,
    LeaseAcquired, ShipmentPlanned, Transfer, Departure, Closed,
    ReportPublished, IssueRaised
};

struct FreightProgramAuditEvent {
    FreightProgramId programId;
    FreightProgramAuditKind kind = FreightProgramAuditKind::Authorized;
    std::optional<FleetId> fleetId = std::nullopt;
    std::optional<ColonyId> colonyId = std::nullopt;
    std::optional<PersonId> leaderId = std::nullopt;
    int charterRevision = 1;
    int shipmentNumber = 0;
    double amount = 0.0;
    std::string detail{};
};

// Actual per-installation operating deltas. A timed day records one duty;
// immediate manual passes record five. Publication of survey results adds none.
struct EquipmentDutyUsedEvent {
    FleetId fleetId;
    ShipId shipId;
    ShipComponentId componentId;
    std::optional<SurveyProgramId> surveyProgramId = std::nullopt;
    double duty = 0.0;
    double beforeUsedDuty = 0.0;
    double afterUsedDuty = 0.0;
};
enum class MaintenanceAuditKind {
    Authorized, Amended, Suspended, Resumed, Cancelled, LeaseAcquired,
    JobStarted, WorkPerformed, JobCompleted, JobWithdrawn,
    ReportPublished, IssueRaised, IssueAcknowledged
};
struct MaintenanceProgramAuditEvent {
    MaintenanceProgramId programId;
    MaintenanceAuditKind kind = MaintenanceAuditKind::Authorized;
    int jobNumber = 0;
    std::string detail;
};

// Emitted when validation rejects a command or a daily process detects invalid
// state. The reason should be precise enough for UI display and test assertions.
struct CommandRejectedEvent {
    std::string reason;
};

// Variant envelope for all event payloads. Adding a new event type requires
// updating persistence serialization and CLI/UI visitors.
using SimEventPayload = std::variant<
    MineralExtractedEvent,
    ShipyardOrderCreatedEvent,
    ShipClassRevisionCreatedEvent,
    ShipCompletedEvent,
    FleetOrderAssignedEvent,
    FleetArrivedEvent,
    ResourceSurveyCompletedEvent,
    SurveyProgramAuditEvent,
    FreightProgramAuditEvent,
    EquipmentDutyUsedEvent,
    MaintenanceProgramAuditEvent,
    CommandRejectedEvent
>;

// Full event record. id is monotonic within a GameState; day is captured when
// the event is emitted so later UI filtering does not depend on current time.
// Payload IDs must still resolve to live records during state validation; entity
// deletion will need an explicit historical-reference policy before it is added.
struct SimEvent {
    EventId id;
    std::int64_t day = 0;
    EventSeverity severity = EventSeverity::Info;
    SimEventPayload payload;
};

} // namespace deep
